### ISSUE TITLE
Instructions? How to really run this?

### ISSUE THREAD

**Issue by Starrcade** [Pascal3366/EasyGentoo#1]
Good afternoon. I've stumbled upon your install script and I'm excited to try this out, however your readme.md did not include specific instructions to running the script. When i'm inserting the install CD, how do i get access to the script? Do i need to use wget? etc. I see a lot of potential to this and i'd like to confidently try this out.

**Comment by Pascal3366** [comment]
yes the script isnt 100% stable but it should work
you can clone it from my github repo but then you have to install git.
just use
wget https://raw.githubusercontent.com/Pascal3366/EasyGentoo/master/EasyGentoo
if you like to get it with wget
you have to have wget installed anyway because my script needs wget to work
